trigger: none

stages:
- stage:
  displayName: Build & Publish
  jobs:
  - job:
    displayName: Build & Publish
    strategy:
      matrix:
        Linux:
          imageName: ubuntu-latest
        macOS:
          imageName: macOS-latest
        Windows:
          imageName: windows-latest
    pool:
      vmImage: $(imageName)
    steps:
    - powershell: |
        git clone https://github.com/keystone-engine/keystone.git
        cd keystone
        mkdir build
        cd build
        ..\nmake-dll.bat
        make
    - script: |
        git clone https://github.com/keystone-engine/keystone.git
        cd keystone
        mkdir build
        cd build
        ../make-share.sh lib_only
        make
      displayName: Clone and Build Libraries (Unix)
      condition: ne(variables.imageName, 'windows-latest')
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/keystone/build/llvm/lib'
        ArtifactName: 'lib'
        publishLocation: 'Container'
      displayName: Publish Libraries
- stage:
  displayName: NuGet Packaging
  jobs:
  - job:
    displayName: Package NuGet package
    steps:
    - task: DownloadPipelineArtifacts@2
      inputs:
        source: 'current'
        artifact: 'lib'
        patterns: | 
          **/*.dll
          **/*.dylib
          **/*.so.0'
        path: $(Build.SourcesDirectory)
      displayName: Download dlls
    - task: PublishBuildArtifacts@1
      inputs:
        PathToPublish: '$(Build.SourcesDirectory)'
        ArtifactName: 'keystone.nupkg'
        publishLocation: 'Container'
      displayName: Publish Nupkg
        