trigger: none

stages:
- stage:
  displayName: Build & Publish
  jobs:
  - job:
    displayName: Build & Publish
    strategy:
      matrix:
        Linux:
          imageName: ubuntu-latest
        macOS:
          imageName: macOS-latest
        Windows:
          imageName: windows-latest
    pool:
      vmImage: $(imageName)
    steps:
    # - powershell: |
    #     echo "Downloading"
    #     Invoke-WebRequest -Uri https://dockerbootstrap.blob.core.windows.net/dockerbootstrap/vs2012_buildtools.zip -OutFile vs2012_buildtools.zip
    #     Expand-Archive vs2012_buildtools.zip
    #     $env:Path += ";$(Build.SourcesDirectory)\vs2012_buildtools"
    #     git clone https://github.com/keystone-engine/keystone.git
    #     cd keystone
    #     mkdir build
    #     cd build
    #     vcvars32.bat
    #     ..\nmake-dll.bat
    - powershell: |
        mkdir $(Build.SourcesDirectory)\keystone\build\llvm\lib\
        Invoke-WebRequest -Uri https://github.com/keystone-engine/keystone/releases/download/0.9.2/keystone-0.9.2-win32.zip -OutFile keystone-0.9.2-win32.zip
        Expand-Archive keystone-0.9.2-win32.zip
        Copy-Item keystone-0.9.2-win32.zip\keystone.dll $(Build.SourcesDirectory)\keystone\build\llvm\lib\
        Invoke-WebRequest -Uri https://github.com/keystone-engine/keystone/releases/download/0.9.2/keystone-0.9.2-win64.zip -OutFile keystone-0.9.2-win64.zip
        Expand-Archive keystone-0.9.2-win64.zip
        Copy-Item keystone-0.9.2-win64.zip\keystone.dll $(Build.SourcesDirectory)\keystone\build\llvm\lib\
      displayName: Download Libraries (Windows)
      condition: eq(variables.imageName, 'windows-latest')
    - script: |
        git clone https://github.com/keystone-engine/keystone.git
        cd keystone
        mkdir build
        cd build
        ../make-share.sh lib_only
        make
      displayName: Clone and Build Libraries (Unix)
      condition: ne(variables.imageName, 'windows-latest')
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/keystone/build/llvm/lib'
        ArtifactName: 'lib'
        publishLocation: 'Container'
      displayName: Publish Libraries
- stage:
  displayName: NuGet Packaging
  jobs:
  - job:
    displayName: Package NuGet package
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        source: 'current'
        artifact: 'lib'
        patterns: | 
          **/*.dll
          **/*.dylib
          **/*.so.0'
        path: $(Build.SourcesDirectory)
      displayName: Download dlls
    - task: PublishBuildArtifacts@1
      inputs:
        PathToPublish: '$(Build.SourcesDirectory)'
        ArtifactName: 'keystone.nupkg'
        publishLocation: 'Container'
      displayName: Publish Nupkg
        