<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Wiinject</AssemblyName>
    <Version>$(WiinjectVersion)$(WiinjectVersion)</Version>
    <ApplicationIcon>..\.branding\logo\ico\wiinject_blue.ico</ApplicationIcon>
    <PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mono.Options" Version="6.12.0.148" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HaroohieClub.Wiinject\HaroohieClub.Wiinject.csproj" />
  </ItemGroup>

</Project>
